server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.152:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/** # 路径匹配
          #中台
        - id: service-item
          uri: lb://service-item
          predicates:
            - Path=/*/item/**
        #==================web前端==========================
        - id: web-item
          uri: lb://web-all
          predicates:
            - Host=item.omall.com
        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=www.omall.com
            #==================web前端--搜索==========================
        - id: web-list
          uri: lb://web-all
          predicates:
            - Host=list.omall.com
# 添加路由
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**

        - id: web-passport
          uri: lb://web-all
          predicates:
            - Host=passport.omall.com
#因为我们的登录令牌在redis，所以yml中需要
  redis:
    host: 192.168.188.152
    port: 6379
    database: 0
    timeout: 1800000
    password:

#哪些页面需要用到单点登录
authUrls:
  url: trade.html,myOrder.html,list.html